### ISSUE TITLE
Gradle Incremental builds break code generation

### ISSUE THREAD

**Issue by edisonw** [sockeqwe/fragmentargs#39] opened 2016-01-27 17:15 UTC
With latest incremental builds on Gradle, env.getElementsAnnotatedWith(annotationClass) does not give all the elements since it only includes the subset that has changed. So those classes will not be generated (which is ok), but we shouldn't throw an error, but instead, continue with a warning and let compilation happen. If there is a real error, an error will get thrown later from using the missing classes.

**Comment by sockeqwe** [comment] 2016-01-27 17:24
yep, I was affraid that soon or latter somthing like this will happen. Until now FragmentArgs has generated a kind of "lookup" table class where all annotated  Fragments were in. The advantage was, that there was zero reflection, but now with incremental builds we always will generate this "lookup" table with just those annotated fragments that were changed (as you already have said, those subset returned from `env.getElementsAnnotatedWith(annotationClass)`).

So we have to replace that single lookup table with a reflection call `Class.forName()` to load the builder. Pretty the same as butterknife does.

Thanks for reporting!

**Comment by edisonw** [comment] 2016-01-27 17:29
I see, I was wondering if that will be what had to be done. Thanks for the pointer.

**Comment by edisonw** [comment] 2016-01-27 18:01
ElementUtils.getTypeElement(className) seems to be the one liner here.

**Comment by sockeqwe** [comment] 2016-01-27 21:48
thanks for hint!
It shouldn't be to hard to fix this, but it requires a little change in FragmentArgs internals.
Basically the problem is as follows:
```java
@FragmentWithArgs
public class MyFragment extends Fragment {

    @Arg
    int id;

    @Arg
    private String title; // private fields requires a setter method

    @Override
    public void onCreate(Bundle savedInstanceState){
        super.onCreate(savedInstanceState);
        FragmentArgs.inject(this); // read @Arg fields
    }
  ...
}
```

So this line of code `FragmentArgs.inject(this); ` does a lookup to find the Builfer class for `MyFragment ` and then finds`MyFragmentBuilder` and calls `MyFragmentBuilder.injectArguments(fragment)`, which will set the fragment arguments.

Right now, this "lookup" is done by invoking an internal class that is generated by FragmentArgs looking something like this (pseudo code):

```java
class FragmentArgsLookUpTable {
    public static void inject(Fragment fragment){
         if (f.getClass == MyFragment.class){
              MyFragmentBuilder.injectArguments(fragment);
         }

         if (f.getClass == OtherFragment.class){
              OtherFragmentBuilder.injectArguments(fragment);
         }
    }
}
```

The problem with incremental build is, that only those classes that are changed are processed by annotation processing (makes sense). But this `FragmentArgsLookUpTable` will be created with just those annotated fragments that are returned from `env.getElementsAnnotatedWith(annotationClass)` (in other words only those fragments that source code has been changed will be in this `FragmentArgsLookUpTable` class).

The solution is, instead of generating this `FragmentArgsLookUpTable` with an annotation processor use refleections and `Class.forName()` to do the mapping from Fragment to Builder at runtime. So we have to hard code something like this:

```java
class FragmentArgsLookUpTable {
   public static void inject(Fragment fragment){
        Class<?> fragmentClass = fragment.getClass();
        String qualifiedBuilderClassName = fragmentClass.getQualifiedName() + "Builder";
        Class<?> builderClass = Class.forName(qualifiedBuilderClassName);
        Method injectMethod = builderClass.getMethod("injectrguments", fragmentClass);
        injectMethod.invoke(null, fragment);
   }
}
```

Something like that is how we have to change the code to ...
So the downside is we have to use reflections (can cache that in a `Map` as "cache") and have to introduce proguard rules ...

**Comment by edisonw** [comment] 2016-01-27 22:56
Oh I see, you are using a lookup table during runtime and they will not be registered on incremental builds or replace the old generated class. Good to know!

**Comment by sockeqwe** [comment] 2016-01-27 23:14
Exactly, the old one will be replaced with the new one which might only
contain a subset of args

Edison Wang <notifications@github.com> schrieb am Mi., 27. Jan. 2016, 23:56:

**Closed** 2017-07-20 22:03 UTC
Labels: bug
