### ISSUE TITLE
Getting weird issues with ArrayList<CUSTOM_POJO> or  List<CUSTOM_POJO>

### ISSUE THREAD

**Issue by TakeoffAndroid** [sockeqwe/fragmentargs#93] opened 2017-08-26 16:49 UTC
I am trying to pass List using @Args but unfortunately  I encountered with following compilation error

Error:(32, 41) error: incompatible types: List<CAP#1> cannot be converted to ArrayList<SMS>
where CAP#1 is a fresh type-variable:
CAP#1 extends Parcelable from capture of ? extends Parcelable

Please help me. I am completely stuck with this issue

**Comment by sockeqwe** [comment] 2017-08-26 20:34
Which version of FragmentArgs do you use?

**Comment by TakeoffAndroid** [comment] 2017-08-27 01:19
V4

**Comment by sockeqwe** [comment] 2017-08-28 01:44
Can you share the source code to reproduce this issue?

**Comment by loentar** [comment] 2017-09-27 07:13
I have the same problem.

Fragment is declared like that:
```
@FragmentWithArgs
public class FranchiseFragment extends .... {

    @Arg(bundler = CastedArrayListArgsBundler.class)
    List<Franchise> franchises;
```

It generates the code like that:
```
  public static final void injectArguments(@NonNull FranchiseFragment fragment) {
    Bundle args = fragment.getArguments();
....

    fragment.franchises = bundler1.get("franchises", args);
//                  ^^^^^^^^^^^^^  here is the cast error
  }

```

It should be cast like this:

```
    fragment.franchises = (List<Franchise>) bundler1.get("franchises", args);
```

**Comment by AndreasBoehm** [comment] 2018-05-04 15:13
I tried to reproduce this issue but with 4.0.0-SNAPSHOT built from latest master i was not able to reproduce it.
After testing with 3.0.2 i was able to reproduce.

I think we can close this as already fixed @sockeqwe

**Closed** 2018-05-13 21:09 UTC
