### ISSUE TITLE
Cannot apply fragmentargs for DialogFragment

### ISSUE THREAD

**Issue by h87kg** [sockeqwe/fragmentargs#22] opened 2015-06-06 11:54 UTC
Error:cannot access DialogStyle
  class file for android.support.v4.app.DialogFragment$DialogStyle not found
  Consult the following stack trace for details.
  com.sun.tools.javac.code.Symbol$CompletionFailure: class file for android.support.v4.app.DialogFragment$DialogStyle not found

**Comment by sockeqwe** [comment] 2015-06-06 12:48
Thanks for reporting. I will have a look on it on Monday. Could you please post the code of your dialogfragment so that I can reproduce it

**Comment by fahimk** [comment] 2015-07-04 03:38
I'm having the same issue when trying to use this with a DialogFragment

**Comment by sockeqwe** [comment] 2015-07-04 09:53
@fahimk Could you please post your DialogFragment code?

**Comment by fahimk** [comment] 2015-07-05 01:41
What parts would be helpful? Here's a quick overview of my setup:

I have a class that extends DialogFragment, and in there
@Arg String test;

**Comment by sockeqwe** [comment] 2015-07-06 08:49
Ok, so the problem affects DialogFragment if you use the latest support library version 22.2.0.

The problem is that there is that there is a inner class `DialogStyle` that somehow is not packed into the compiled sources because of a internal compiler error at google.

```java
public class DialogFragment extends ... {

    ...

    @Retention(RetentionPolicy.SOURCE)
    private @interface DialogStyle {}

    ...
}
```

This will issue also affects other Annotation Processors like Dagger and AndroidAnnotations.
The issue has been reported here:
https://code.google.com/p/android/issues/detail?id=175086

The current state is that this one will be fixed with the next support library release which should be in Fall 2015 while releasing Android M.

Possible workarounds:
 1. Setup arguments for  DialogFragment by hand
 2. Use support library 22.1.1
 3. Define the missing class manually and add it to your source code.

I think the easiest solution right now is to set arguments manually for dialogs.

**Comment by sockeqwe** [comment] 2015-10-29 10:21
Seems to be fixed in latest support library

**Closed by sockeqwe** 2015-10-29 10:21 UTC
