### ISSUE TITLE
Generated code needs cast

### ISSUE THREAD

**Issue by kubode** [sockeqwe/fragmentargs#23] opened 2015-06-10 13:06 UTC
`bundler-parceler` fails compile by class cast.

build.gradle
```gradle
    compile 'com.hannesdorfmann.fragmentargs:annotation:2.1.0'
    compile 'com.hannesdorfmann.fragmentargs:bundler-parceler:2.1.0'
    apt 'com.hannesdorfmann.fragmentargs:processor:2.1.0'
```

fragment code
```java
public class SkuListFragment extends Fragment {
    @Arg(bundler = ParcelerArgsBundler.class)
    Item item;
}
```

generated code
```java
  public static final void injectArguments(SkuListFragment fragment) {
    Bundle args = fragment.getArguments();
    if (args == null) {
      throw new IllegalStateException("No arguments set");
    }

    if (!args.containsKey("item")) {
      throw new IllegalStateException("required argument item is not set");
    }
    fragment.item = bundler1.get("item", args); // compile error
  }
```

I think it needs a class cast.

**Comment by sockeqwe** [comment] 2015-06-10 13:11
Thanks for reporting, I will have a look this evening

**Comment by NammariMarkavip** [comment] 2015-06-10 14:36
@sockeqwe I got the same issue !
the problem is incompatible type in this line
fragment.item = bundler1.get("item", args); // compile error
the library returns Object type instead of arg type !

**Comment by sockeqwe** [comment] 2015-06-10 14:37
I see, you can expect that it will be fixed until tomorrow

**Comment by NammariMarkavip** [comment] 2015-06-10 14:44
quick solution make ArgBundler accept 2 generic types and in ParcelerArgBundler make it <T,Object>

           public class ParcelerArgsBundler<T> implements ArgsBundler<T,Object> {

             @Override public void put(String key, Object value, Bundle bundle) {
              bundle.putParcelable(key, Parcels.wrap(value));
           }

           @Override public T get(String key, Bundle bundle) {
           return Parcels.unwrap(bundle.getParcelable(key));
        }
       }

**Comment by johncarl81** [comment] 2015-06-10 15:42
If you're comfortable assuming the return type is the same as the input type (which maybe isn't that much of a stretch), you could use generics here instead of a cast in the generated code:

```java
public interface ArgsBundler<T> {
  public void put(String key, T value, Bundle bundle);
  public <R extends T> R get(String key, Bundle bundle);
}
```

This would be directly compatible with the `Parcels` utility class:

```java
public class ParcelerArgsBundler implements ArgsBundler<Object> {

  @Override public void put(String key, Object value, Bundle bundle) {
    bundle.putParcelable(key, Parcels.wrap(value));
  }
  @Override public <R> R get(String key, Bundle bundle) {
    return Parcels.unwrap(bundle.getParcelable(key));
  }
}
```

 and push the cast to any others:

```java
public class StringArgsBundler implements ArgsBundler<String> {
  @Override public void put(String key, String value, Bundle bundle) {
    bundle.putString(key, value);
  }
  @Override public String get(String key, Bundle bundle) {
    return bundle.getString(key);
  }
}
```

**Closed** 2015-06-10 20:08 UTC

**Comment by sockeqwe** [comment] 2015-06-10 21:07
Fixed in version 2.1.2 that I have released right now. I apologize for any inconvenience this bug may has caused!

**Comment by kubode** [comment] 2015-06-11 01:17
thank you for quick response!

**Comment by NammariMarkavip** [comment] 2015-06-11 08:05
Thank you .
